### ISSUE TITLE
verwijzing

### ISSUE THREAD

**Issue by Aaltje24** [Sjieuwe/PsycholoogMiddelstum#19]
Zo verwijst u
U geeft op uw verwijsbrief aan welke vorm van zorg uw cliënt nodig heeft. het is van belang dat uw cliënt zich digitaal bij ons aanmeldt. Een voordeel van cliënten is dat zij bij 1nP zelf een regiebehandelaar kunnen kiezen en dat 1nP nagenoeg geen wachtlijsten kent. De cliënt kan zich met de verwijsbrief zelf aanmelden via deze **link**

Een format verwijsbrief die u kunt gebruiken als verwijzing voor vind u door hier te klikken op verwijsbrief.

Moet worden:
U geeft op uw verwijsbrief aan welke vorm van zorg uw cliënt nodig heeft. Het is van belang dat uw cliënt zich digitaal bij ons aanmeldt.

Link: https://public.extenzo.nu/aanmelding/#/professional-selectie/professional/13197

hier (te klikken) : https://1np-strapi-production.extenzo.nu/uploads/Voorbeeld_verwijsbrief_1n_P_61bf8edd4d.pdf

**Comment by Sjieuwe** [comment]
@Aaltje24 Ik heb het nu toegevoegd, maar ik zou als ik jou was toch nog even naar de tekst kijken, want ik vind hem niet zo lekker lopen
